apiVersion: v2
name: monitoring
version: 0.1.0
dependencies:
  - name: grafana
    version: 0.1.0
    repository: "file://charts/grafana"
  - name: prometheus
    version: 0.1.0
    repository: "file://charts/prometheus"
