{{- if .Values.ingress.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: {{ .Values.servicePort }}
    targetPort: 3000
  selector:
    app: grafana
{{- end }}
